export function getDomRefs() {
  return {
    canvas: document.querySelector("#canvas"),
    pageTabsHost: document.querySelector("#page-tabs"),
    languageTabsHost: document.querySelector("#language-tabs"),
    languageActionsHost: document.querySelector("#language-actions"),
    translationStatus: document.querySelector("#translation-status"),
    pageMeta: document.querySelector("#page-meta"),
    addTextButton: document.querySelector("#add-text-block"),
    addTableButton: document.querySelector("#add-table-block"),
    addImageButton: document.querySelector("#add-image-block"),
    imageInput: document.querySelector("#image-input"),
    openDocButton: document.querySelector("#open-doc"),
    saveDocButton: document.querySelector("#save-doc"),
    exportPdfButton: document.querySelector("#export-pdf"),
    pageSettingsButton: document.querySelector("#page-settings"),
    pageSettingsModal: document.querySelector("#page-settings-modal"),
    pageSettingsClose: document.querySelector("#page-settings-close"),
    docStatus: document.querySelector("#doc-status"),
    formatSelect: document.querySelector("#page-format"),
    orientationSelect: document.querySelector("#page-orientation"),
    gridSizeInput: document.querySelector("#grid-size"),
    snapToggle: document.querySelector("#grid-snap"),
    aiPanelToggle: document.querySelector("#ai-panel-toggle"),
    aiPanel: document.querySelector("#ai-panel"),
    aiPanelClose: document.querySelector("#ai-panel-close"),
    aiTarget: document.querySelector("#ai-target"),
    aiInput: document.querySelector("#ai-input"),
    aiSend: document.querySelector("#ai-send"),
    aiStatus: document.querySelector("#ai-status"),
    aiResponse: document.querySelector("#ai-response"),
  };
}
